defaults:
  - _self_
  - task@_global_: cartpole_swingup
  # - override hydra/launcher: submitit_local
  # - override hydra/launcher: submitit_slurm

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
egocentric: false
device: cuda
save_video: true
save_train_video: false
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  actor_activation: relu
  with_gait: false
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  encoder_losses:
    fwd_loss: false
    action_loss: false
    inverse_loss: false


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
 # launcher:
   # timeout_min: 4300
   # cpus_per_task: 10
   # gpus_per_node: 1
   # tasks_per_node: 1
   # mem_gb: 32
   # nodes: 1
   # submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}/.slurm
